### ISSUE TITLE
Maybe change reward to also care about "centeredness" on the target

### ISSUE THREAD

**Issue by Kolpa** [hpi-www-midl-text-localization/text-localization-agent#16]
currently only the IOU is relevant.
Should we also evaluate the relative distance of the bounding box centers?

**Comment by bakoe** [comment]
(belongs to text-localization-environment to my mind – see hpi-www-midl-text-localization/text-localization-environment#33)

**Comment by Kolpa** [comment]
Accidentally added this to the wrong repository
